version: "3.7"

services:
    app:
        env_file: .env
        # image: node:12-alpine
        # image: purplefrog/todos-app:${APP_VERSION}
        image: purplefrog/todos-app:80
        command: sh -c "yarn install && yarn run dev"
        # restart: always
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./app:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DB: todos
    mysql:
        env_file: .env
        image: mysql:5.7
        # restart: always
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: todos

volumes:
    todo-mysql-data:
