version: "3.7"

services:
    app:
        env_file: .env
        image: purplefrog/todos-app:${APP_VERSION}
        command: ["node", "/app/src/index.js"]
        ports:
            - 80:80
        working_dir: /app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DB: todos
    mysql:
        env_file: .env
        image: mysql:5.7
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: todos

volumes:
    todo-mysql-data:
