version: "3.7"

services:
    app:
        env_file: .env
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        # command: ["yarn", "install", "--production"]
        # command: yarn install --production
        # command: sh -c "yarn install --production"
        # command: sh -c "yarn install --production && node /app/src/index.js"
        # entrypoint: ["node", "/app/src/index.js"]
        restart: always
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DB: todos
    mysql:
        env_file: .env
        image: mysql:5.7
        restart: always
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: todos

volumes:
    todo-mysql-data:
